spring:
  profiles.active: local
  application:
     name: accounts
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

security:
  basic:
    enabled: false

---
spring:
  profiles: local
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
eureka:
  instance:
     nonSecurePort: 80

     securePortEnabled: true

     securePort: 80


---
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN
