server:
  port: 8080
#
#eureka:
#  client:
#    registerWithEureka: true
#    registryFetchIntervalSeconds: 10
#    serviceUrl:
#        defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localsadsa:8761}/eureka/

security:
  basic:
    enabled: false

pivotal:
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK