spring:
  profiles.active: local
  application:
     name: quotes
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    serviceUrl:
        defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8761}/eureka/

security:
  basic:
    enabled: false

---
spring:
  profiles: local
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
---
logging:
  level:
     io:
        pivotal: INFO
     com:
        netflix: WARN
---
api:
 url:
   company: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
   quote: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}

#https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.quote where symbol in ("{symbol}")&format=json&env=store://datatables.org/alltableswithkeys