spring:
  profiles.active: local
  application:
     name: quotes
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
---
spring:
  profiles: local
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
---
logging:
  level:
     io:
        pivotal: INFO
     com:
        netflix: WARN
---
api:
 url:
   company: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
   quote: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}

#https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.quote where symbol in ("{symbol}")&format=json&env=store://datatables.org/alltableswithkeys